sudo: required
dist: trusty
language: java
jdk:
- openjdk8
- oraclejdk8
env: GRADLE_OPTS="-Xms1g -Xmx3g"
script: gradle build
notifications:
  email: false
deploy:
  file_glob: true
  provider: releases
  api-key:
    secure: $KEY
  file: "./build/libs/foxguard*.jar"
  skip_cleanup: true
  on:
    tags: true