sudo: required
dist: trusty

language: java
jdk:
- openjdk8
- oraclejdk8

git:
  submodules: false
before_install: git submodule update --init --recursive

before_script:
  - bash ./setversion.sh

env: GRADLE_OPTS="-Xms1g -Xmx3g"
script: gradle build

notifications:
  email: false

after_success:
  - for f in "./build/libs/foxguard*.jar"; do mv ${f} "./build/libs/foxguard-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SNAPSHOT.jar"; done

before_deploy:
  - rvm 1.9.3 do gem install mime-types -v 2.6.2

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/foxguard*.jar"
  skip_cleanup: true
  on:
    tags: true