sudo: required
dist: trusty
language: java
jdk:
- openjdk8
- oraclejdk8
env: GRADLE_OPTS="-Xms1g -Xmx3g"
before_script:
  - sh ./setversion.sh
script: gradle build
notifications:
  email: false
after_success:
  - for f in "./build/libs/foxguard*.jar"; do mv ${f} "./build/libs/foxguard-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SNAPSHOT.jar"; done
before_deploy:
  - rvm 1.9.3 do gem install mime-types -v 2.6.2
deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/foxguard*.jar"
  skip_cleanup: true
  on:
    tags: true